apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ysJlSV9hLfRSCAqB3pcdF2w4KznMZIkVEohEKOK3C/P5Hpc6IOvFZHFg+esl0tAV/0rp7H1MQqWu7agVbuKF3Yg2UHjkEGoTQkv0vetWrwgRxpV99RMN1SfoTMnKXMLlrzlRcyc9HTIT5+SGVMETo7sS+3EezGcVQIeSd1ZGyZEqgzMgevwWWMw4e3lBtKjAtsk8DL2Kx4HH9Eq0orzWtHnnRIG8kqvqCsmrp66BFC69C9wr88QCbQfGOw9EfVl904oPB//X3GY1kckUlg7PGtgmq4SSnIw78AO7GRQ5NKpv+8roXibpVFSKyIyxIus240H3cJ1xVnIfd4g+BplP7xLj1OsqM3AAKoXVB4ms0+uh9cVdJkfwJ7nJRFl+Im+C,iv:24WoNHZC93VpcAhJes1meQka7uXzoLQGVDXIr79mNIE=,tag:72H1165o3KS7LGUIb1p2TA==,type:str]
    identity.pub: ENC[AES256_GCM,data:neSIOhyOqIif3m8Xv4sU2UB/voBHYtSVjnoYhhKl2AXIZ8AtHRqoc3XaXtO5tTcLfOdDJVw59ndUN2gHS9Uu/usqpxhBqWrCTVp9/w4k0nc5qPYZMoD1m+B3oPHO+3dbpkJ0z4e0mkDtx2XN0S6WHPTTozlyIxDt+ZqUHrnM53VPzwAbqOMVcPbx/8Pa4bgWFdkU5iEkUUz+2UW5t77oNPqZ7e1JTVzo9SRVm2dVTolsQSIxS8WBZtxXKtOkvMoGqMUtVXgcuyOlP6uXSw==,iv:SnobTzHHoweOuDxPgMQxq0yt9qg52wLUXUpUaEDm8R4=,tag:ssjg26XyYm5Bv6DcTzFelA==,type:str]
    known_hosts: ENC[AES256_GCM,data:AasBhCtGYpYfC27Cjj7afOv8PI+tZMxnSL93fOR4muIq2JzlXnjNjwFx063DpqXebBGz98Yhyf5mH55MhVbwKx61uCy1EGz/qkZphuntGqu1YKJnH0d9P2pJ+a5g0DfNiLXxiXCDpDuh9t/48msQkWVYGzNW4eKlx2hrxaKm5v/uEaktazr/RaQVQIsk71bKrZNnCfgRBfD9+kVLnVqhAMK+UWP13fa/S6Jo,iv:XhrEb/RmZ78FKyielgSoiyTuq9NgTh5WXwY5wN+dnAk=,tag:ru4rjpCC+Wt5TH95HmyGgg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ2pXNHRyQ2lMQVZhOWVF
            SkJGZlRmMnpTL2Z1cnhSSWpiMkx2RE9YaTFRClZuci9MVjhPRWhNVWJ0QWdNdjB6
            MlVoSFNCWFFVdFdHNVJwRCs5VmFkYm8KLS0tIFZQSDVicGZmRTFpTjRXMnhmOFJL
            cEtoeS9uaFFhb2tIcWNmWndOL0M4WUkKkyxzT29yPhN4T5cvwKNiw2qnwmTG7Aoi
            9592lV5P7dcZWsVJfPFBSAqRGYuX7qF/DhkfEAQPnfZiDtGKVuOslw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T08:03:58Z"
    mac: ENC[AES256_GCM,data:yrT0sjV0EFZVFRNS7ax4PXYHDrvlZN39l1snlUP8ggZYCAomSgu73Rex5XHiZrXmK/txeg5xwa4gUIkUCNXo/KFtPeQTBYCsMaOhNdT/wuKhM9cLl/3VdVW+Uk7eBH0/Hxm1EX6EL0wzVNx8h7iWt5ViVRgA+11cK9NQXsBMu/o=,iv:Dk4X49DmmbdrPcXIzEpqRzzaobe+HRkg+Ek6MuQHSyI=,tag:KLiRaOJdyCOsnI6qBP79GA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
