apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gI6n+jg3Izec/07DfywznLk6310cXvxHMbnpE8ulNbQJcd2B/9FqCIyI7cPqvNyEn87jz/zr5JacudL8PM4pKTCDcTkW29UhqJDlWE7d6QLG+Zyr/wXz7VzY/RVBSgeiV8IVTX/MEx6Y1hBfZu75FOJNtMdhDCe5LpvG/Po5p+vAs3SRrWnY/4Zj19RUOkk9CXdc8cbuESZjff6+t7rc5rlY4za1vrP3o/1WPrD9QXfK88FAeshlI2mgkM90mfKMQekH+qbHxfNUcggKY7EGJvmDb8lNe4raaIeRCar1gLTciKrE6a4qrJOQ5/ORg1GKYo1jxJxEWoTjrIjpSaxng43TbVRaZVvI3moC3eQpFQaq/HNd7TNafvQ8gUHzTPs0,iv:DIvghh//dzae0cM9Db69tBOUr/q6uubsvx2LFSmEId4=,tag:1zAu72ze6i1wntbhD5nwTg==,type:str]
    identity.pub: ENC[AES256_GCM,data:MbzF3T+1gWufaNq4vdL2CiRq20zj40egj57gTv1eSB5qU0YTveoNvVTFqaD8zcnQ6R3G5Md5UmPoXN+KJN6hxPqAI4n4iTNiRPa2dPb8zD8/sRPUKNbc0BclZMoRQcifphOvqyNHcLDwAlCECgo7U48u031BzV2kDN3Oju7Yo2R2+1Q6UZBKMb5VkUBce34T48CA31BC79OHhygMeMDfUGEYjGAk1pueClnXzxAp786UDUOSkusZphTJTlxerPrxMlo3/s4jPeP4tsXyOA==,iv:xbXd0MBiZmCF4PubYEzqwSOcsRfdWx/0Gy96JpauWXE=,tag:RItOHDEp4igAIDB+BGbvhw==,type:str]
    known_hosts: ENC[AES256_GCM,data:tt7c4AFBijOiywpNiuXPk1/unqN5e6lSZOW7dEcPlTImIjKnqKX4i5DmuD7KpQobX9ahoTDazMuh+d8otABIyp0qF+YZV1ewQsFwe3XxMX/3QMvK98JLXUvt+ahIs6Zfzg92V3wYJMjZkyol0bbLMSzLQazpSHiD28ui5PZpjTZHRYa++7Wq7856JI3fs948m8U1iMnlHgTHBwiNBEUjTv3zjf7WQbiQy+C+,iv:PzFsfSUsREym8r+x5GzPHma3FIvcgxdkoUrMbVC1LWA=,tag:MqylR/gIdAPj47K1WPP9IA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaTNMWTZoTFh6SEd2blNE
            aHlPT0RXbk80eG02TUwzemR4Tzd1ZHZrL0ZBCkNabDJGYko2SmJ6N3UyeUdsYkFC
            a0FpRTU2ZWxBTlBtcEtleTNheUtsMVUKLS0tIFFkQ2hSSm1LZFdJVGlhY0pUa083
            QSsvZ2MyNmtlaFcwZ2d0Vi9Uc2crZDgKWN/DiPGNxVG8GIAxhBhoHUc5HKy0A+64
            4XHWEodJQRo3UTkNc9V2HUKA8++8Y1m9jEqcalDArf9w8lIAd9b/yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T09:54:29Z"
    mac: ENC[AES256_GCM,data:3V7+zT8gpvmzjIi/qhSaRhY3pYaG4UWhzuZZA37at6/hVy8eHQyvXfd6T0cVqzjOLP69CRQ/Az0heMsaxI7ygbMRXAnAMhgjRuYuL0K+0OF/bwpNVJsIaukpzmbAhkCoecsv506MT86iPDjE6pjqYnFJ7fGQWhtOGbiY5pIEZEo=,iv:9roOxVsKINbTkz3csUTL5GCCsLwuE9S9gzZMTio2mwI=,tag:fYfWBC4dOMhh/0sjRDHbdw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
