apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:b/o2bBWMDxZ+twjoDcC2vd4KOVBMnwU5qTKzDO+XSUZ/nG2nZjAc49oznnLxiVihpK0bKASIp5ASW5HgaIvyFFI0Pw6ZbflCCFq4usODNzzGWO4SwR93fxmBQU7aiHTXumvJlX22cRovd6IUZLJN7NBgsVCYgjlZSGF2eHCP7R/XOQ48IvYtFpquSuZGugFFSEcbtv5g2EPTmQHdS4GsQdU//doYq3J3h+AcD/20nma86wdwtmtRTEsmWlwKiblwv62IXdXf23Whz28A+1nZumzhKPugRWc6lVgV6V30YkRevVxljx3vTU2EUN7ouNn3LAhHnP/tQq0EmOSs1c4ZcdG5VEQtoOWBEUmj++Q+xPLH+ujlEUytVcLizKMc7F3b,iv:ttvN0i6EbyomieIwa/Q+U+HyQqXwOhj6pcaY21H+Cs4=,tag:BV+KdU3pnaOizFoxdTXvmw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ow8ZTj2l7rSP/zQobzuGS9DdsFK38GZPLBsTK/GSM92DeKyInI/qsFukc0PWzLBkMug23CM8DLv3dTRI2+KHl5RIzmR6UBX7MWLgr1O9TU76TBV1cNx2RCK+YyLh6ZuDyfept3fcwsH5RUhnQu8262MNH4ztUMxWT2dzt4HxbB9RlkG7sJZUPQ7zO/GGsbMB/Dg8klVeZMPbdf4cUtcJlAKZjjCEdTjC2PxiIzcUIE8LkGWV/miJs/a+Pgh+sFnApOB6S+NYZgdho44rKg==,iv:TTy2hORUNwSqM+KHr/n5j+EBBmDo/SL2CCq7QPl5jSY=,tag:zStumnB3Wbeyv+q+VVJztQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:I/SS2qWhYNk/zAeSs6g/mf7C2UtKyiUkgiXPCXzfRD0omRBTFXJMd11Uh646VU87C6QwuNoWhTRVGYNwEvdF77bEX2YrDfD5ZXhtlsJUEXFf1Wpfubrc0w/AYRWdyhbdf5hQHAblDytca5qKHBs6FSV0CzKAxoEpN/jK1DRhGl9S0thkaQGpYdNf1+5x+64WIpili5iLOv/3q5S4nUsDSTw45hIPD66e1sfJ,iv:O7svVwa9y3lOifhbgwKISRm/m6YKuM1Po7JKGFpRIJg=,tag:5H4OQXn+k2Kg2mwwoIKGDg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRmhibisxejZLNzIwTFAx
            a0trOEQyUTdCd2FqZkh6K01QV1YxRTAxMEJJCi9TYU9yaXozRUgycDRDa2EyaFlm
            a2pVa3NjcUF6OUV4aC9STENuR2lwOGMKLS0tIE9HUS9ZdHNURWwwOVZOYkY0YmM3
            TG1PK3l6cllRcHArdHNIZVhtOWVOUjAKhH+nSrozWRdscKEgJxgiPpuF74b6hHrT
            JmVFTlJJ4r0NgcSfiqWt4Fhq3VveyXHlJpU71qA7EU2PwRo345QHlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T00:28:35Z"
    mac: ENC[AES256_GCM,data:SGbw9QHSFvzRBFpluTPhqiCBv8cHaoUHtANRe6n7GUdMeb80PSbRNZ2ZyrS6x8kOGllrUVLbzIs5C8rnxb6g1kPYfWqKR4mG1djH58lhoV+Bztr4mqv91JYp1D8w1A5BeXH1FCwLOZ4gg9pKTwU/iTrB3U9VI7ZRClHoqEr9IwU=,iv:91Y0iHBSgtKaeonAc5HT1rfagZMwdfdJWYLh+5I05n4=,tag:xBNSmQUMrj7AtMSO3d14Ew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
