apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cIixfAupFiGlx7bJIXVmxO0JM2ADVNpqrFkKdwRYFStjkbPwx5XK7lvwO0n333Z5jSJS8s1loWyFXy9ruj0PjgNSfdD6gVA34KUpc8mKRXxujBN7j/mDDnJsUStAaIn4S/UY4LYuUNJTtQR3OulNXoKzvsJ0JDCusT8Pe59SwL27IEgwDTq+cPPMkCPYsZetJXdYBBikeM9jm/nudKM6zT0fqhnK2z3e94XIvkC9BnOvj/tAkJcdMWE+f1SwRDzwb8sqI0yuUAoXrfzZHF93aXBSm5g6Tyw7DCmvcBwKwcyVg3Z0Bo1DeylWfyxHxHjvh3t8CiA9mGFH0yis/qF4hLTRAi9Vx1Y9mdQdL++9AsGqtHLBzPrHQfz94Uxwyrzt,iv:dCDSfw0Rb3uk/AAwyCdKwMAwRVtofFYi/mS8DQGD6Lo=,tag:WbISIHqVyfdxhEmFUk9CWw==,type:str]
    identity.pub: ENC[AES256_GCM,data:UdoPs2qd76tvsz8qVjYfaoaC1W6WDTVLC/ea1CBEEzrCmq31W5xBgO1F3dvCcb0twMVKpzIORUtwNH35kjKvfnVyNCWRfSEZb3W0ZeyQag8FciVtYQaq0WbLVPBLTZaDDp27dndaa6L5Ep68hrKxL3G4nKbDbZ4SJzIguPfmnopZDroDVj3s8o2sS8BM3ZoggAHTtx+G4tcSXIs5YfNkuhwiTF9XGsf5Sf/IK0s5WphHQScQjs/CW1N2iE8Hd2K8XGtJqKKobYBkBxvkgQ==,iv:JYgV9WQSFl05wkYgV584Aui6/f6bVXvVagJMEe08lqM=,tag:bPJc54habCrEFnR5VAhVqQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ywmDZ13uXkRp0YYHAaG3eUCetFBp5fT3FCTNQfvkYwAGKI56hiVJMwcsZ0gQOcXmV8LIAhK477Pr6FfMInAtIBEzGS1vwmzXd+goCqTW0ptcgGdjuvukMMsp4Qrd6Novsy5fXBDXAoQL/RREJi1C8J8oVOv0nMXvuxnVHAUimHk7ZjYqNtZ36dMHMsz11i7XVOn1J0ywXB92JLz4/pAyjQgLlvDN7SSqZhNl,iv:YJfMSR1ioJnV4gHsVtACAETa7bX7Ji4DYjR3yYDxJ8M=,tag:m0uwbfwmL1KdbLXEsOgOUA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNTY0UUhiQjV0c3c0bWZQ
            UnQwdml2OHRKc2ZkVjh6aGVEeGtTZlB2S25ZCndhMEVRMzZrRmM0Nmx5SUE3clgz
            QkNRRUM2eUNsN1ljaU9tYjhCdkxtWXcKLS0tIHVPaUJCeWROVWQ5bGZDMW85Q3dP
            NWFxTUQ5Y0hyZFh3RW12MklyNjFRb3MKGw5+EUMKoTmmKXIwgxkpD9OneBFoDBpB
            WVCZqKIAwdVMSNgAuWFU/NCwyZ7OCdylpFy5ANf1/eBTl1gZM2aq6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T08:23:03Z"
    mac: ENC[AES256_GCM,data:YZD82LtMo4awo1cLrq1TjC2CLiyU3rhILhGCteoEFNXGzH/Gz3cUIPJHVpmdlhAH6A/qFNxAvFkXYC99F0Dehy1YOhqbJQU9P3M70ylojhqXUDsVFDt9rEAcnE8JmiAGm/qLMS3ultz2lcq9QlEFs40muUkygSR/b45nIa91lx4=,iv:hCJ5MiLpLVPGZQjJ+Dbioq5Nzx7RgGOj81+wU7N6/Fs=,tag:z9axrKykk9oMGfgUueSKIA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
