apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:p+fi3JJUmnFYd6tJh2rJIkXKcMCkbs62X+ci9Qc5atpwoIZo7QSIQqsulUV8zXTjilibCzT8gfft687GkurtmPAiCDb0T6Z4GrLzGpxc43At50jiNuxVfegdhzgFRsduWeQYEEk1zBIL1EeLgkfRMgPmA8/TGp2VJS3tMeHknq+mtGg02ARkEV7z80zJIyXgoAlX/F7oVue+1tmQ1jat6FR23HGA7zDiHEOV23xRe3uYQ49nhqFlPboPn2iQKXUXa8Bha2tdRd7jqntDq7DJp2P3nzsjURynvRREFKm6u3cngSTM+HNgKI9SXe7mPizVwWlhoAgMo3iBDSQ+eDRdNuENSXlTmDQiMHrUgTS0mtkIhBjP/zdsCevLVh/jNIZK,iv:okmIth9bRzTFAQJrY36Rzb0OSWLOlsg9gyoMVd2J8L8=,tag:XEmm60qtMc+6DFtcfRM7gw==,type:str]
    identity.pub: ENC[AES256_GCM,data:7Fu89It1qfQTA90Idzrim+YaY+RBgDrf/mCTZB65e6OqhSIiW//IEiAbwBjXnPd2zMr18unDX7LunNqFY8S3WcT/9Wgq5WUW1Yjrtc4bxPm6+dFiSdbWroL08je133cUzkxNrgVRSnqPLk0g1A2Fdx3j7Q4sxuz2OKDKDdgEU43zmBPgAxmngjggxO1Zp5LArAtUccN6V3gvGJH7dN+jIgOOu/gqcpKTksAozp8bOJ1eqysuk0wwl4F9xAlRC4TkdpDPZN8wpSy1AqnZ/Q==,iv:FdFHfAyERrBcu+Z2YDPkVDGH3rfKV8tU1Be8bmHZmA4=,tag:xllF6IyFN3ugSOHP6LS+YQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:LoonVqJMHzGcnb+qzE5I6AcxgDIqCWwm752cSlPbi4u07nzacFf8UgGhTYjgb3v8fLexdyNQKCKZYWG0wPRxv3e3thquhD2mCM5Hy6teboN39/KeDz+BVsH5IoHI57KTzvpfDgnaf/SsgsYvmv7ztbfBH3TlqwLpgX9n8m5c3NfXtmaOsTN47qFpCnO/aikz5fORs3v4TLSlA9NRBa6AzuW4E/qyiFOQ/Xg0,iv:a/68+zt8XEjQXPze8uxb3cLIhCGdjKm4dFWaVUYbhdM=,tag:EgfjQP2j9vme76NLW80XgA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYUZPczFNK3MyelhHZ3NO
            eFZHQUJtSnZ1bFZEdHNwZnp3NlRlbjBNUldBCk1MaVpEU251NFB0N25aS2xtUE9t
            YWx1OVV2WUlTL0JXR25wNm5tY3JidzAKLS0tIHN0NVYrUk1qdlFtZ285OUNlUXdF
            MjRGNjJyaTRPWmU5K0x1UGZwR1dwKzAKx8knEGnhckv2VJsyjpdIkSUOdMRY49Jr
            +qkSQX6uceV2sShmupCQwLxSrvu0xA3dhliWE2SiuBerFFix9nT3lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T17:39:43Z"
    mac: ENC[AES256_GCM,data:TAcO/M/fozlEe/OLNZZnq4+ZjiEGB/EEG489E7Cj7FJCJIPNnEciEN1eG8CvQ0is05mdkGbwwWwg1c9qGgsWd/bZHt+p3pLpMTWOacjgD73eXhZdZz5EuMM6aqg3LirSKYbsJQ4pGtKTmA5fhSsbQQZ6NsIet99xm70G8fhyh1g=,iv:41t4+2ncsfKC2x9i1TSvbsRnIuQMlX5aMSp1mK3rbrQ=,tag:GWS6h+x+qM7GHK6dBwnxhg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
