apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/gHv4xk1iP+1c867obU1zs39V8t7XTGi12BjGboN79PvViM1bnfliCy7vXYUcGjGfyGaFPYyxQ1RkE4e2swgEDRSSiFDt9g2RzaLqrbUsX60LB6aUojPudbE/LcaUA3Wm5nkI4DGxvv3qQmsSbIvLmAMkW6/h5TLdIH4eREIWcR4ec6ai2dDkhL76C/JTkwRsgc7C+omo1uwvgx8r5g94Hr604ICI0SrN4Tw/FkhOhLAo3z0zFs26YTnDhoX76Ube8DnybaqW4lqlAPI8hsaqdvSi+dFZPrZZnoPPVdYudQemlSxrWVwF5oGbGfbTkSOzrw2A0adT4gdMvq6VgDe0jRfdFTSXgOR8/4/W+q8Ybm108MM0eF9o5P9LaKfNgKo,iv:k+jUr3SbXEK89/3CEBd3ha1sEm3wWp4mbLIxe4Tjk3M=,tag:rldcLZn6tzIl1aET6NZfKA==,type:str]
    identity.pub: ENC[AES256_GCM,data:vEnB9QDM8+ZGOr0dzVeD+RV0tma9euv20nhrzk2Z9fWrrpCaxqC68QYfDRPJ/ILd+ZCLSN5N6+bHEfe5q2hR73N62cRrUzoB1Dez7ElAWeHhWBZQ4rcFoIezcodZDMl5pgkYK6JDBtM8BQDU2ENm+pzGyKOK0ZST+y/K3fxadzsASdOfnZKOALH2iFieYUV2Bm3mzBiGrhdaXSBVOeyFNXDKB4BFAAISO4YdTtHH0sOS3Q5/0pGDDCC4yISohxg6wGmGKwOYam8xro3S2A==,iv:pXWd+y8996BuAqCjQU07lOnQ5AEPzGUrh23CeuMowSo=,tag:lv4qUD61axAkEGESiVK30Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:EGJHo0IlLO/xPgiXaiGPhhx1CSKX8jCppyY4qLQfk8r9AX2Qe3e2iYifLC0GfMsSCbLYrub6PKAxtPCUwPBpVDaPqUzX4ovyV6pekgEE5yrzfoXr5J9HKIMy/xmc4Xmz2lMFcjFc+IWR5tmRF1Cdvk6ZeGkkb+FOExXQdsflK0hFspTN1JohwW/ns3Kb+etzxZqlQQsj0lEFGOdbvXzsh14ZP6YM5sAq9MBm,iv:IdBCDFcTR9ZZCE+8felaS4ekZ1LktGuVCMH1FM5ZP+k=,tag:MNciR7bciXD6TL54CeeSfw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc0diVzNQT2Vvd0kwNDZ2
            SUlpNm9YM0lVQ1drNTljNVhmQXZhamtkZVZjCjhQSkxNU1lNWVlaWTJCQkpKdTlI
            dmFvYzkzWlVqNnFhUDZaL1NrRXFuSUUKLS0tIGcyZUdCMGlpRThSOCtFM0ppeWpC
            NXZOMG5sbi9xUzF5ZXIzcXRZOW15VmMKfPpSw+ZyANEqyuqcUVWwG86HC0kQPOhh
            3b96/OvD9YtKAoeK9cZeuL27nUSI0qS0bFWqyqFSNhw+/Vt/qFtUxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T08:07:26Z"
    mac: ENC[AES256_GCM,data:wPLWlwlDfqAUSolp9i5aH+w0nfAp0WiqyLIBt8/5kw82UuGstj5bxx5khc91uCkcw0CbPJGPJGxRIHvyhagkRicaEd6j0GCOfez3NoLVq2HTdAlx2HNO9fPnou7arheSPNc6Xb9IIrxAEhUBh6asNF2+fvVUxRhZbOa2Qxd0t6A=,iv:byT9a3hz78xDQ1bVG4rlc4ZsKjXv8q1uFT+Qs2QCzKs=,tag:eqElOsSMYNn+TwfF0zeQpw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
