apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fJ/jXfBrBT9cuGYSRlUQqxWnaAiJo6gne7d7lc4oqQoaDec8E7HCCPOQCvCdt1uQlgdl8eXWo8CIq2w/hNO+X0CDYqTclIiwjSN5pNxrcrdqbXoYSZ9qZ/SeX/rU1TXp5FKtQ3fXk8E/HsDm8Qw+NmnMiXi5rfcKOLkFkMDzTQgt/hGCuWWA8RhOu8lPh8VygJ3L9yM3FSzMC18Fwccs2TQR5/En6Ocs9kEzl0h97Ns/02VWOm3WVnsaCMxncSlUBxa+hBMwC8d95/WtzoqlQGbRKLq4oaFtLhpqoMfLVUwg54IOtmKA+nGS4wRHauIy7eGkiTkk6aE4svsgzdgIHHQcAQPtXZBlHDE7XABsBeyCDi4Fns9HgxypgtIvKvMO,iv:A4ak3Oh5cGqStCF0UZ3d1GilBEQAMYSnkw3inh7O+Z0=,tag:XDIQLA1DzRH3UC5snV+4gw==,type:str]
    identity.pub: ENC[AES256_GCM,data:4wvs7qnDlMLpUc4m1zuQadBZfyvLK23CU7CEDiUncRlopJPO/go7eZFXUCIhH1wImt2JRylT1HBwMVBGivx+5HfaTvEqAlhW+xyGzX/JleJdeUuL4wDjMU1wH5agA+DGZKeEiNThg7CiyBxTs46ECBnhE96qGuIF1XoSAj3yVRQiZwcXsR91cTvpRKIviQOgWp5uZacPeobW8iT+4vYWyivQTchi8XplKhFEL1UMvrhl1XrJWfHw60oYakLP07DT92elN0Nuubvh4Urhwg==,iv:NN72wIM20Ll+O1Iyy8nFjZlL5ZutrzlNWSP1Pb4n6+k=,tag:dMFKICZ59rMyFoo0zp97xA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ANuG8yKIgAhlHfGpCTBiZl5vrDsF8xaIcYORMp53PDzFVgRvnwEMDsoTTY2i2CuUXY0Gjd5zO8MVaBTzfl7/TVyjlXS7mRkekJ4iD+JRy8tIcN/uYwh92BwBc0E19RmI7YwVhzs2sEKVkrvi8MQDMf02yh4N/KRXjFSCqycQRQroCMKsw2wGFm8TWff71w88hIe7htgBUsTduyydZjMbzkKZCjfMd6yanahW,iv:FxdUi4+TT4keImkB05O2jSo20XvJOy2PKwNZi/tSHhQ=,tag:SWZDlY/Tiy1RiWxf+vu4qQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaL2g3N2ZyQkxxOEw2TFhN
            bE1sMHVPeFV1eHErdWZNZ0FRZ3Y5WlIwZ1FVCk8rWHpmSVYrZlVSRUVjVlJDd2ti
            Q25aZ2FZZS9SQ2JEeWZjNzdOUWFRNDAKLS0tIFVyTk01NVpqcGQ4cmkyVXkwZmpQ
            TlpvdUhzTkQ5L09KL2E3WW5qOUJoTDQKxgMamkRUEbKByzxLKGMjk35RvGotcq+G
            7GjVYDMnfc3cNIaXoVyr2c65NTRpn1OcvRuCOfTbgK8K7r2zJAwinQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T05:03:39Z"
    mac: ENC[AES256_GCM,data:l1Hc/uDjclIlcTarKzzBZyOV5UZ11b6qqBuBVPvKEg95yxBxxTXDvsv4xTbE+qrpujDK9Wz95wXWEzIfmrqN7qWz1XWQXfb+VYgP3pXlNyZvPLCa8oNUtNlmgWR6PDRIvXBufIApoq2jhV1eto5O5mCWwBccwu5tP9vpE2d2NZk=,iv:UlJH3fCqHhur2QuwuhGrRMwzRreoBDhs5qozS3lDnvM=,tag:n4gOjXslDCKxnWmVHec5NQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
