apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wOmB6w25CJziEVHotvJWfIQgBcN/zyvO05bsHFrVfiCVwUeixnS4m+ULn2qK8XQQpJewd8oSpOYA+K5DNyMV8w0wpaaJrNALvN065YIr+RVG5VJCsZXT5UDdyyOplsCXU80E2kbeR2H80QmZ5Tj1DeezoUspSHLdWZk/7sb/ZUcGjgn3FAx+sPQeLPNun/3Em0rh8vKl0ndJiupT5glsiUIPYEwA4MynFQD14r/4Xpjb0lpq88JzxIw+jPbjYhJUZyGKYltEFGvuN2aAGmiFYbmDaqKBgjXvCNKrzuMM9+UumVTTUB8JVzbPzLw9Gv4gqACNi9iNNIxfFe7JZy7AfnzAfloXuDkuDjFOJbEL0nUccFi+iSybM/5Gwsl7XHLL,iv:uzgzdc8myyu8iWn7ueDrMpLhThpCE0caqfqwjXFLP54=,tag:p22Yrv31gsuLRIA7fuFeSg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ry3TtCxIqQZpEsZicocLoQxMVD4DTbnp/57+Q8y10+pADdxZBojU1CIpth40+y1M6Xtsm1RZ6+NsEnpXpSXAUU+li/2uqMV0GkY7qJ1iATWDVtgmW1FlBFuYo62/pS3HD45Fhi+gaU+ZtGaX74ejdcE6q+aXjWHQzcsdQAYTnnxawoUYmoEk+P2DQX27nOJMD0Fx0LMwoiIzC+OtQpvgS7CPBMwng+OvcFz/S6xYmf+iGwkhTcLQlPM6qnKiTHr/Z22wKlUoxUko092pMg==,iv:/nPOMW5Q+Fp3C7dlnceELndNn2bYoW9AAOxGUIprAwA=,tag:L7NkQ+2EuBdbm6XodDZLJA==,type:str]
    known_hosts: ENC[AES256_GCM,data:4JvxAwSkq4Tdq3iM+VMk2B/E7WnekD91b4foy+2rf3pGh09okallOYcnQO0h0KR8vk/E5ybKpaydnAh8yZ9cg0Wv4GFpxdg0+psXcvnkWPuCWWCNd5muJZOQyXzOkNBSLjSsx39dflCPSIL4qUxJxbOVffckF2nVTzBVWFC2lmxEmGTVsciJrt+zY6yyZH+Fmo9az8KtJv2qvN9g4McIPAWvWeTWKVXH5dWq,iv:kjEhQFwEkzlTgK1wgxou8zPdpIQqZ2F1wX61U0yiZI8=,tag:Abm8Fq38YsDBdlfCN8eDtw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVFRiTDAvUE5CR3V5citl
            bHNJeTlyMXl4eFFpWEZQZktNNExoYVdxQmhrCkgrT01KdXNtY3dmSGh4cDNGd3V2
            Y1lYOXp4N3J0ODlHbDZHV1JHVlFCN0UKLS0tIFhDQjFDNmZ3azBCRThOYTd4NzBt
            QndGR0dnbVZCckgrQWRoYytvN1c3Sm8K9qZjU9n4/d5CJ/JANgD81krOSo8G3o6R
            S1N4WkcwHLDxmFbDpvO7A6OPrCWGCnH4FBdQcWV4FOTwdDvxRCbKBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T00:29:24Z"
    mac: ENC[AES256_GCM,data:II8CkINLmcTvGZk/iWuDlLjawe1qHWVlZH+LsAH8d5N0wGLgcG5WcPKkSCJ1HwCH/QpW1RUgp+dO6m5xAoXASCyuYE7Fj6HJFM5CQtVbXQXNfW+38r8b1ut11XhMKOozQChbMXYuK204Am5OFhBKJRVsRvJwmvjwIAFVjaQrBZE=,iv:g0aRr+Gt//LKwNIFoAEt+GCjAlickv/63kUeVm22Tg8=,tag:LAUoJ1fk1VarUhHza8neLA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
