apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LYtD9m2Fm3oZOIrdl7IzkaOqdXbA02/arkjv6HRJ06mDZsvZRHINvhTm9TFkVru7koQNx78pZI8gIys5/czYJiO+v4rb/ZppiKplDiYKFz9ULbjJsGuMCVZmS2BPI7VzQ/Mm6EZ1x7w8SylBfLtb2gSEyllwuD5whq3XzR2p8ckJFsd5K93vb6NK0eF2ueYtWSxLeNcBhsbbKBdyD8hO1PL2B0BwHEvEst3CsGOkXGm7C3Xo2Bf1jzYQTEH6xDLpR+n6g6DEEnvnbvE1s5mcVR2gooyzIqVy9+q/1iR2k53pDeWTjpNsTrF/csuODlWhnndKTaTCZSQSjMC6UVnq9eWJDMGgEu6Qs4TD+GT43xA2rBQZ7h9meE/FvlWp4Cx6,iv:AjKEQYWwLU2Z3uJsS1KqRlCpEt8YaWln7XcojeDj2Mw=,tag:oLPky1tFHxfpbH2gpzRIFQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:DVGdk62Z+n+rXXb4K439QVXmAwnqOOfQcVoeLX6FeoF9HONgL4JBRvlHN37JSJW4J5RfQD8D/3X/+JS0bOPZQfqbBzN8aj2pEg1pmMnoUURTU/8aARO8x59vuTthVHGhdJ8SZXTWmyGBHTP2+hNr1cVD5PRnj1TdoVNDWDDYm/hQjjYzbHtbIQax8rPleBQs1eTrNJRZKQ8sFGYDfEsQXAF2tPSve/2vJ0DvnRpVj9W7JI96yQkIocvtVejbHmpSgurEL7SnElOfmen3mQ==,iv:XJ2xjo9QY7b5aXI2LQ/WsB2kZY7KXcvY1v/eXBjNygY=,tag:uaipL1KdLAjy5cIP+vDhEA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yACU6UWaC4T0wkhETKmgWRFC5+2j/HlUBkdmg1y1c5tgnWRrUKHgXRZemEIi6gMajk3E7uCu7gAbZA1SffocNIlk47s2Soha+aEZDpSGGPzaYTXZAv+mMcGWRIW2jA4ij8mkMpvhF65G1jdfG5qLk+AfGew4EH7toIwI2PdPBS85nuzonXz317u3Xt8wOvdhsxJvbwOJ2btyJfBHEwjjzw5+sSTlAFf+N2Re,iv:lxU/GJpKxFfrZl46tGqpqqvpUuodc6uPqcCXc4K/54o=,tag:SdqjGUfCYW5fCfn5HaymqA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZUtKbUNmckZXSThWNmwy
            Q3Qwb1hldWV1TVpKMWlPaTdoUzM0bDN5WERVClZQSVYxTk1McGxNaU1wdWwvNUVV
            TVRBMmxwaUkwM3FoOGVpNmpOQ1padU0KLS0tICtIS01WcUNDZVlINDlXWnZTbjBV
            MW02N01OQWhuY2FEZENZN2VocjZUUUkKntx5BsDdCTk6GyJ0sKpZvphrumXPRdEY
            amCpjK0sI6o3q/h4vcaY6pRlkqIQEbibC8iXTcZRveKYhzh5mQfbwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T00:01:08Z"
    mac: ENC[AES256_GCM,data:QgUT8R7ax3BxFXdTmbBU9lXKKNgSqXYBPkBekuRPZSRzsF6ZBduorDGsipXx5Fohi8SfWoZL/H7JBK+ombzTWOu9i7j1IMG33WWT0jlMGBv1KDghD87fjfH7s7vGOc9D4JxJo7dKod85t/KKDh6Jqo2Ql5GPPq+AVYjk3klgk38=,iv:Dfb1nj75IHK5xp18zkP2+RIzAkVN/ZtYD1YOUNgWDlw=,tag:SnIq+dXBVRoFPC9S7EKmgQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
