apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:12Rl5vf9l39woFX+x1vfoYLZ9k08ERs9+0c+6Ujblrigm4fc2KOhn1AdoqUhR5awiosN2hYJTwP3nldj7YoAsqeVSuqisCqg2m3RAgVWtZ+BQCEv+B89wlhftML8mHgXWnmv3Z6C1eHPBqG5ASwqYBv+Ckfi0Md+c1bz3PyJ5F+Z4WExHHDdirigquBhCF91nt8aQLITHQN7Ly0j7qHt/o3/2p/4Cj+I8UE9VA1REaCrd9t39WFBnffCZ2Rr4g0IYGXSrmv3BpsY5d7KLtLXzl/E6AtdiO0EzBGrT6tjII9eM5mbTU3jbQDDo4V4RcBg7mG6MV5mwV3+suNzICE0Zon9knwT4eq8IWzFDXCxlkUsHhCqf/8ZrHnJAkUQofgh,iv:LPNtfon8DWPcc9V6Dh/tQwk4mFBjbPtUCb/QjhX7Uis=,tag:eoZkt74KHBgTxqDILHY67Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:spxcaT+GteqGfyzC4OTF2s/7QEeAwBMXsOMrhvIa6RJ78nD3Zb3A2LGHOIFdjpYwADQAyTx0FiQhV6Z4msEBCwolAK9UgGvoee7aexqHCOO1Alk8PrCrnp1PiYo6TrbjEeVSyyKdVOh5MY2BP46Fn3MBgk0lZFnoOiMdd7Rw50Fgdqntkffec3FPwOmnViU74z9Ela+4xxtIpdBYxOiguD5agjOnmSsjexx/6cfnyPNynudneMMDsR8BOnmDc9Sq0lK43ohnNqDnf5a8xQ==,iv:clhh6IYW4lvdWaXAFxkHopdaDEr11IhE4nGrY/a5Cro=,tag:VsYNbyNKd71fKmjKNFQR6Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZkadRMFkRfrYp3EokSi/wh+k1Vy7D8xKSbjjjMK9j/TjsLx3BBry3fTzCdS8pXsPhe4LLie5O8Th2vrLnPZQbjrRezzkmJnngPagsCX2pAMKcBCbFk+dhApAV0W4vfjcvCMSjJvFpxWAmh2M7m2GGzguTtcXR4H39MRjjzS2oJnvKbi65S9Fjfda6ZbqQulHa+xph3FzshioFxgfMiEZISfuWR6jXjNsWK7J,iv:fAGj+92at341xAHTDnaNgLD1jXJLpJ/kWTNHyR4cBEo=,tag:QPbZVw+uU2hBjdkCO5LpKg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1fxr2mjtfjy0t755p2tmemttj4ft70sgffhv0ax99v6agutqh6d6shh439a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMmJDL2F2eDlOeGpVYjBa
            eDFWaFliUHlaRUZJbURzbmpKQ3NrNmRGaGlZCjRGeDVhd1hzbFM2VE44L1dLcGN0
            OUJGWlZCcXUyaHNpMlJ2ZWE4NlV0OGMKLS0tICswNUpydnZ1RFRvUG1NUnZJdFhP
            aWwzNVcvb1JFU0wxR2UxT05IcnFpbGsK1ZzeeQ55YMFhwPQsptx+nDB/hJ2IVzUU
            eetlwYMK95gxPOhrCHSuwEuto8Xr6NxjMqdTddA8zijYSg2i9+wuUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T17:08:22Z"
    mac: ENC[AES256_GCM,data:OLOo5PBELKL1dLxB4XlZIbw7gJZCkFczuUpoQgNUOdFxmwyMgoRkXghx0wHCxTzF7wB452x1jW700lZLQmwhgdyHJCHt5Y1Htf5KwTJT1bN4T78qzo//WLJshFylJYGTyLvmujO8befOJ+j/VmVuBYaqE5ap2iKvAqPD9teRqx8=,iv:uBcDl7um7DEeBHnVGCcXi5H89152V+5tZ4RLIgxSgwQ=,tag:KtaG0eB1Ey6IolBvSOA3mg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
